name: publish

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Getting all of the md file contents
      id: collect
      uses: sguthals/talkswithdrg/2020/ignite/intro-to-github@main
    - name: push
      uses: actions-x/commit@v2
      with:
        email: sarah@guthals.com
        name: Sarah Guthals
        branch: main
        files: "/2020/ignite/intro-to-github/ignite-shareboard.md"
        repository: https://github.com/sguthals/talkswithdrg
        token: ${{ secrets.MY_SECRET_TOKEN }}
        force: true
