name: publish

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Getting all of the md file contents
      id: collect
      uses: sguthals/talkswithdrg/2020/ignite/intro-to-github@main
    - name: 'Create a file'
      run: ${{ steps.collect.shareboardContents }} > ignite-shareboard.md
    - name: push
      uses: actions-x/commit@v2
      with:
        email: sarah@guthals.com
        name: Sarah Guthals
        files: ignite-shareboard.md
        force: true
