on: [push]

jobs:
  update_shareboard_job:
    runs-on: ubuntu-latest
    name: A job to add learners to the shareboard
    steps:
    - name: Getting all of the md file contents
      id: collect
      uses: sguthals/talkswithdrg/2020/ignite/intro-to-github@main
    - name: Write File
      uses: DamianReeves/write-file-action@v1.0
      with: 
        path: ${{ env.home}}/ignite-shareboard.md
        contents: |
          echo "Hello World!"
        write-mode: overwrite
